export const API = {
  SET_MARKET_LIST: 'SET_MARKET_LIST',
  SET_SHOW_COMPANY: 'SET_SHOW_COMPANY',
  HANDLE_MARKET_LIST: 'HANDLE_MARKET_LIST',
  HANDLE_LOADING: 'HANDLE_LOADING'
}

export const UI = {
  HANDLE_SEARCH_MODE: 'HANDLE_SEARCH_MODE',
}